-- MySQL schema for Digital Banking Fraud Detection & Simulation Engine
-- Database: fraud_app

-- 1) Create database (run once, or adjust name as needed)
CREATE DATABASE IF NOT EXISTS fraud_app
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE fraud_app;

-- 2) Users table (supports both normal users and admins)
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(255),
  aadhar_number VARCHAR(20),
  account_number VARCHAR(34),
  mobile_number VARCHAR(20),
  bank_name VARCHAR(255),
  ifsc_code VARCHAR(20),
  branch_name VARCHAR(255),
  is_admin TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3) Transactions table
CREATE TABLE transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  -- Link to the logged-in user
  user_id INT NOT NULL,                    -- FK to users.id
  -- Form fields
  user_name        VARCHAR(255)  NOT NULL, -- Display name entered in form
  sender_account   VARCHAR(64)   NOT NULL, -- Sender Account (UPI / A/C No.)
  receiver_account VARCHAR(64)   NOT NULL, -- Receiver Account (UPI / A/C No.)
  mobile_number    VARCHAR(20)   NOT NULL, -- Mobile Number
  transaction_time DATETIME      NOT NULL, -- Transaction Date & Time
  location         VARCHAR(255)  NOT NULL, -- Location
  current_balance  DOUBLE        NOT NULL, -- Current Balance (₹)
  amount           DOUBLE        NOT NULL, -- Transaction Amount (₹)
  -- System-generated / engine fields
  fraud_probability DOUBLE        NOT NULL DEFAULT 0, -- Fraud probability (0-1)
  ml_risk_score    DOUBLE        DEFAULT NULL, -- ML model risk (0-100) if available
  average_risk_score DOUBLE      NOT NULL DEFAULT 0, -- Combined average risk (0-100)
  risk_level        VARCHAR(20) NOT NULL DEFAULT 'LOW',  -- LOW / MEDIUM / HIGH
  risk_category     VARCHAR(50) NOT NULL DEFAULT 'Safe', -- Human category label
  final_decision    VARCHAR(50) NOT NULL DEFAULT 'Normal Transaction', -- Final decision message
  transaction_origin VARCHAR(50) NOT NULL DEFAULT 'manual', -- manual / auto
  is_fraud          TINYINT(1)  NOT NULL DEFAULT 0,      -- 1 = Fraud, 0 = Safe
  fraud_reason      TEXT,                  -- Reasons from rules + ML
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_transactions_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
);

-- 4) Alerts table (for unread/read fraud notifications)
CREATE TABLE IF NOT EXISTS alerts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  transaction_id INT NOT NULL,
  user_id INT NOT NULL,
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 5) Password reset tokens (OTP-based)
CREATE TABLE IF NOT EXISTS password_resets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  otp VARCHAR(10) NOT NULL,
  expires_at DATETIME NOT NULL,
  used TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_password_resets_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
);

-- 6) 24-hour statistics tracking for simulation
CREATE TABLE IF NOT EXISTS simulation_stats (
  id INT AUTO_INCREMENT PRIMARY KEY,
  stat_date DATE NOT NULL,                    -- Date for the 24-hour period
  total_transactions INT NOT NULL DEFAULT 0,  -- Total transactions in 24h
  fraud_transactions INT NOT NULL DEFAULT 0,  -- Fraud transactions in 24h
  safe_transactions INT NOT NULL DEFAULT 0,   -- Safe transactions in 24h
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_stat_date (stat_date)
);

-- 5) Optional: sample admin user
-- Replace 'admin@example.com' and the hash with your own values if needed.
-- Password hash here is just a placeholder and should be generated by the app.
-- Example (DO NOT USE IN PRODUCTION):
-- INSERT INTO users (email, password_hash, full_name, is_admin)
-- VALUES ('admin@example.com', '<sha256_hash_here>', 'System Administrator', 1);

